
/**
 * Constants for action types in Reports view.
 */
export const reportsActionTypes = {
    DONWLOAD_SURVEYS_EXCEL:'DONWLOAD_SURVEYS_EXCEL',
    SET_PANEL_EXPAND_REPORTS:'SET_PANEL_EXPAND_REPORTS',
    SET_PANEL_RELOAD_REPORTS:'SET_PANEL_RELOAD_REPORTS',
    SET_PANEL_COLLAPSE_REPORTS:'SET_PANEL_COLLAPSE_REPORTS',
    SET_PANEL_REMOVE_REPORTS:'SET_PANEL_REMOVE_REPORTS',
    SET_BOROUGHS_AND_SITES_REPORTS: 'SET_BOROUGHS_AND_SITES_REPORTS',
    SET_SITE_REPORTS: 'SET_SITE_REPORTS',
    SET_BOROUGH_REPORTS : 'SET_BOROUGH_REPORTS',
    SET_REPORTS_SURVEYS_SUBMITTED_LIST:'SET_REPORTS_SURVEYS_SUBMITTED_LIST',    
    SHOW_VALIDATION_MESSAGE : 'SHOW_VALIDATION_MESSAGE',
    RESET: 'REPORTS_RESET',
};