
/**
 * Constants for action types shared across views.
 */
export const sharedActionTypes = {
    SET_LEFT_MENU_EXPANDED: 'SET_LEFT_MENU_EXPANDED',
    SET_RIGHT_SIDE_EXPANDED: 'SET_RIGHT_SIDE_EXPANDED',
    SET_TAB_CHANGE: 'SET_TAB_CHANGE',
    SET_LOGIN_USERNAME: 'SET_LOGIN_USERNAME',
    SET_LOGIN_PASSWORD: 'SET_LOGIN_PASSWORD',
    SET_LOGIN_REMEMBERME: 'SET_LOGIN_REMEMBERME',
    SET_LOGIN_ERROR_MESSAGE: 'SET_LOGIN_ERROR_MESSAGE',
    SET_LOGGED_IN: 'SET_LOGGED_IN',
    SET_LOG_OUT: 'SET_LOG_OUT',
    SET_LEFT_MENU_TOGGLE: 'SET_LEFT_MENU_TOGGLE',
    SET_TOGGLE_PROFILE_MENU: 'SET_TOGGLE_PROFILE_MENU',
    SET_DOCUMENT_CLICK: 'SET_DOCUMENT_CLICK',
    SET_LEFT_MENU_SMALL_SCREEN_TOGGLED: "SET_LEFT_MENU_SMALL_SCREEN_TOGGLED",
    SET_RIGHT_MENU_SMALL_SCREEN_TOGGLED: 'SET_RIGHT_MENU_SMALL_SCREEN_TOGGLED',
    SET_ROUTE_ON_MAP_OPENED: 'SET_ROUTE_ON_MAP_OPENED',
    SET_ROUTE_STATUS_ON_MAP: 'SET_ROUTE_STATUS_ON_MAP',
    SET_COUNT_INSTANCE_STATUS: 'SET_COUNT_INSTANCE_STATUS',
    SHOW_VALIDATION_MESSAGE_SHARED: 'SHOW_VALIDATION_MESSAGE_SHARED',
    SET_ROUTE_ON_MAP_OPENED_LOADER: 'SET_ROUTE_ON_MAP_OPENED_LOADER',
    SET_SHOW_CONFIRM_DIALOG: 'SET_SHOW_CONFIRM_DIALOG',
    SET_DOWNLOADING_FLAG: 'SET_DOWNLOADING_FLAG',
    SET_ACTIVE_COUNT_INSTANCE: 'SET_ACTIVE_COUNT_INSTANCE',
    SET_SELECTED_COUNT_INSTANCE_ON_DASHBOARD: 'SET_SELECTED_COUNT_INSTANCE_ON_DASHBOARD',
    RESET: 'SHARED_RESET',
    SET_CANV_START_DOWNLOADING: 'SET_CANV_START_DOWNLOADING'
};