
/**
 * Constants for action types in Admin view.
 */
export const manageSitesActionTypes = {
    SET_BOROUGH_SITES_MNG: "SET_BOROUGH_SITES_MNG",
    SHOW_VALIDATION_MESSAGE_MNG: 'SHOW_VALIDATION_MESSAGE_MNG',
    SET_POPUPLOADER_TOGGLE_MNG: 'SET_POPUPLOADER_TOGGLE_MNG',
    SET_PANEL_RELOAD_ADMIN_REFRESH_MNG: 'SET_PANEL_RELOAD_ADMIN_REFRESH_MNG',
    SET_BOROUGH_MNG: 'SET_BOROUGH_MNG',
    SET_MANAGE_SITE_DIALOG_OPEN: 'SET_MANAGE_SITE_DIALOG_OPEN',
    SET_UPDATE_SITE_DETAILS: 'SET_UPDATE_SITE_DETAILS',
    SET_PANEL_EXPAND_ADMIN_MNG: 'SET_PANEL_EXPAND_ADMIN_MNG',
    SET_PANEL_COLLAPSE_ADMIN_MNG: 'SET_PANEL_COLLAPSE_ADMIN_MNG',
    SET_PANEL_REMOVE_ADMIN_MNG: 'SET_PANEL_REMOVE_ADMIN_MNG',
    SET_SITE_TYPE: 'SET_SITE_TYPE'
};