
/**
 * Constants for action types in Dashboard view.
 */
export const dashboardActionTypes = {
    SET_DASH_BOROUGH : 'SET_DASH_BOROUGH',
    SET_DASH_SITE: 'SET_DASH_SITE',
    SET_DASH_TEAM: 'SET_DASH_TEAM',
    SET_FILTER_ROUTE:'SET_FILTER_ROUTE',
    SET_ROUTE_PROGRESS:'SET_ROUTE_PROGRESS',
    SET_MAP_KEYWORD_SEARCHES:'SET_MAP_KEYWORD_SEARCHES',
    SET_MAP_KEYWORD_SEARCH : 'SET_MAP_KEYWORD_SEARCH',
    SET_SURVEYS_SUBMITTED: 'SET_SURVEYS_SUBMITTED',
    SET_FILTERS:'SET_FILTERS',
    SET_ROUTES_DATA:'SET_ROUTES_DATA',
    SET_PANEL_EXPAND_DASHBOARD:'SET_PANEL_EXPAND_DASHBOARD',
    SET_PANEL_RELOAD_DASHBOARD:'SET_PANEL_RELOAD_DASHBOARD',
    SET_PANEL_COLLAPSE_DASHBOARD:'SET_PANEL_COLLAPSE_DASHBOARD',
    SET_PANEL_REMOVE_DASHBOARD:'SET_PANEL_REMOVE_DASHBOARD',
    SET_FILTERS_ON_RELOAD:'SET_FILTERS_ON_RELOAD',
    SET_MAP_LAST_UPDATED_ON:'SET_MAP_LAST_UPDATED_ON',
    SET_SURVEYS_TEAMS:'SET_SURVEYS_TEAMS',
    SET_SURVEYS_BOROUGHS:'SET_SURVEYS_BOROUGHS',
    SET_DASHBOARD_ERROR_MESSAGE:'SET_DASHBOARD_ERROR_MESSAGE',
    SET_LOG_OUT:'SET_LOG_OUT',
    SET_MAP_JSON_LOADED:'SET_MAP_JSON_LOADED',
    SET_MAP_NO_ROUTES_FOUND:'SET_MAP_NO_ROUTES_FOUND',
    SET_LOADING_SURVEYS:'SET_LOADING_SURVEYS',
    SET_ROUTE_STATUS_ON_MAP_DASH:'SET_ROUTE_STATUS_ON_MAP_DASH',
    RESET: 'DASHBOARD_RESET',
};